### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by Youjinium** [niveK77pur/VinLudens_Music-Sheets#2]
Dear student

Your ReadMe is outdated. Please assign this issue to Misbah.

Cheers
NG

**Comment by niveK77pur** [comment]
Everything has been migrated to a new GitHub account. In the process, everything has been updated as well! This repository will be archived soon, please check out the new place and open issues if anything is outdated again! :dagger: 

https://github.com/VinLudens
